### ISSUE TITLE
Add responsiveness to Amazon 2030 page

### ISSUE THREAD

**Issue by manoharv2512** [sakshimadne/Design-Discus_013#34]
IN footer-2, footer-3 and footer-4 need to add responsiveness.
Need to add animations.

**Comment by manoharv2512** [comment]
Hi Rahul,

You need to add slider animation to cards in section-2.

**Comment by rahulsharma998** [comment]
Completed

**Comment by manoharv2512** [comment]
Great Work & Thanks
